version: '3'

services: 
    
    nodeserver:
        build:
            context: ./app
        ports: 
            - "5000:5000"
        networks: 
         - nodenet
    
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "8080:80"
        networks: 
         - nodenet

    db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - nodenet

networks:
    nodenet:
        driver: bridge
    