version: '3'

services: 
    node:
        build:
            context: ./app
        entrypoint: dockerize -wait tcp://mysqldb:3306 -timeout 30s docker-entrypoint.sh
        container_name: nodeserver
        hostname: nodeserver
        ports: 
            - "5000:5000"
        tty: true
        depends_on:
            - mysqldb
        networks: 
            - nodenet

    nginx:
        build:
            context: ./nginx
        restart: always
        container_name: nginx
        hostname: nginx
        ports:
            - "8080:80"
        tty: true
        depends_on:
            - node
        networks:
            - nodenet

    mysqldb:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: mysqldb
        restart: always
        tty: true
        volumes: 
            - ./mysql:/var/lib/mysql
        tty: true
        environment: 
            - MYSQL_DATABASE=nodedb
            - MYSQL_ROOT_PASSWORD=root
        networks: 
            - nodenet

networks:
    nodenet:
        driver: bridge